# Ports of the local network (sourced). The 298x block stays clear of
# vlpds's migrate e2e (278x) and its dev server (2620).
RELAY_PORT=${RELAY_PORT:-2980}
RELAY_METRICS_PORT=${RELAY_METRICS_PORT:-2981}
PLC_PORT=${PLC_PORT:-2982}
REF_PDS_PORT=${REF_PDS_PORT:-2983}
PDS_BASE_PORT=${PDS_BASE_PORT:-2984}
MINIO_PORT=${MINIO_PORT:-2990}
MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT:-2991}
export RELAY_PORT RELAY_METRICS_PORT PLC_PORT REF_PDS_PORT PDS_BASE_PORT MINIO_PORT MINIO_CONSOLE_PORT
